### ISSUE TITLE
Exception during each decompile

### ISSUE THREAD

**Issue by Lanchon** [caoli5288/java-decompiler-plugin-cfr#2]
hi,

thanks for this plugin! it works in Android Studio, but it produces an exception for each decompile:

```
jar:///[...]/patched/build/intermediates/dexpatcher/dedex/classes.jar!/com/[...]/BuildTypeConfig.class: stub:[PsiMethod:BuildTypeConfig]; mirror:[] [Plugin: com.i5mc.idea.decompiler.cfr]
com.intellij.diagnostic.PluginException: stub:[PsiMethod:BuildTypeConfig]; mirror:[] [Plugin: com.i5mc.idea.decompiler.cfr]
	at com.intellij.psi.impl.compiled.ClsFileImpl.wrapException(ClsFileImpl.java:389)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:357)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getDecompiledPsiFile(ClsFileImpl.java:398)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.renewFile(TextEditorBackgroundHighlighter.java:65)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.<init>(TextEditorBackgroundHighlighter.java:57)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$PsiAwareEditorWrapper.<init>(PsiAwareTextEditorProvider.java:140)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$PsiAwareEditorWrapper.<init>(PsiAwareTextEditorProvider.java:134)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.createWrapperForEditor(PsiAwareTextEditorProvider.java:131)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorProvider.getTextEditor(TextEditorProvider.java:161)
	at com.intellij.openapi.editor.ex.util.EditorUtil.isRealFileEditor(EditorUtil.java:65)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.isRealEditor(EditorGutterComponentImpl.java:1266)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.getGapAfterIconsArea(EditorGutterComponentImpl.java:1411)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.getLineMarkerAreaWidth(EditorGutterComponentImpl.java:1305)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.sizeHash(EditorGutterComponentImpl.java:699)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.updateSize(EditorGutterComponentImpl.java:682)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.updateSize(EditorGutterComponentImpl.java:678)
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:579)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:193)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:169)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.createEditor(TextEditorComponent.java:165)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.<init>(TextEditorComponent.java:100)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:93)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:86)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.createEditorComponent(PsiAwareTextEditorImpl.java:71)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.<init>(TextEditorImpl.java:52)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.<init>(PsiAwareTextEditorImpl.java:44)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.createEditor(PsiAwareTextEditorProvider.java:47)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$6(FileEditorManagerImpl.java:872)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2453)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:971)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:788)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$4(FileEditorManagerImpl.java:770)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:86)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:770)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:711)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:151)
	at com.intellij.codeInsight.navigation.NavigationUtil.activatePsiElementIfOpen(NavigationUtil.java:197)
	at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:173)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:235)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:245)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:53)
	at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:31)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:130)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:122)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:443)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:59)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:627)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.psi.impl.compiled.ClsElementImpl$InvalidMirrorException: stub:[PsiMethod:BuildTypeConfig]; mirror:[]
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:300)
	at com.intellij.psi.impl.compiled.ClsClassImpl.setMirror(ClsClassImpl.java:422)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:278)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:303)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:291)
	at com.intellij.psi.impl.compiled.ClsFileImpl.setMirror(ClsFileImpl.java:294)
	at com.intellij.psi.impl.compiled.ClsFileImpl$3.run(ClsFileImpl.java:350)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:198)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:347)
	... 86 more
```

thank you!!

**Comment by caoli5288** [comment]
Yes. It's java editor's issue not decompiler's. It not break any decompiler's function.

**Comment by Lanchon** [comment]
thanks!
